require("dryngler.plugins-setup")
require("dryngler.core.options")
require("dryngler.core.keymaps")
require("dryngler.core.colorscheme")
require("dryngler.plugins.comment")
require("dryngler.plugins.nvim-tree")
require("dryngler.plugins.lualine")
require("dryngler.plugins.telescope")
require("dryngler.plugins.nvim-cmp")
require("dryngler.plugins.lsp.mason")
require("dryngler.plugins.lsp.lspsaga")
require("dryngler.plugins.lsp.lspconfig")
require("dryngler.plugins.lsp.null-ls")
-- require("dryngler.plugins.autopairs") -- autoclose "", {}, etc.
require("dryngler.plugins.treesitter")
require("dryngler.plugins.gitsigns")
-- require("dryngler.plugins.formatter") -- using null-ls formatter / linter
